# Generated by Django 4.2.27 on 2026-01-06 03:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datasets', '0002_initial'),
        ('gestures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelArchitecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('encoder_type', models.CharField(choices=[('stgcn', 'ST-GCN'), ('transformer', 'Motion Transformer'), ('hybrid', 'Hybrid ST-GCN + Transformer')], default='stgcn', max_length=20)),
                ('decoder_type', models.CharField(choices=[('transformer', 'Transformer Decoder'), ('lstm', 'LSTM Decoder'), ('ctc', 'CTC Decoder')], default='transformer', max_length=20)),
                ('encoder_config', models.JSONField(default=dict)),
                ('decoder_config', models.JSONField(default=dict)),
                ('num_parameters', models.PositiveBigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'model_architectures',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TrainingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('batch_size', models.PositiveIntegerField(default=32)),
                ('learning_rate', models.FloatField(default=0.0001)),
                ('weight_decay', models.FloatField(default=1e-05)),
                ('max_epochs', models.PositiveIntegerField(default=100)),
                ('early_stopping_patience', models.PositiveIntegerField(default=10)),
                ('optimizer', models.CharField(default='adamw', max_length=50)),
                ('scheduler', models.CharField(default='cosine', max_length=50)),
                ('random_seed', models.PositiveIntegerField(default=42)),
                ('full_config', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('current_epoch', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gpu_info', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('architecture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_runs', to='training.modelarchitecture')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_runs', to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_runs', to='datasets.dataset')),
            ],
            options={
                'db_table': 'training_runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkpoint_type', models.CharField(choices=[('best', 'Best'), ('latest', 'Latest'), ('epoch', 'Epoch Checkpoint')], default='epoch', max_length=20)),
                ('epoch', models.PositiveIntegerField()),
                ('file_path', models.FileField(upload_to='checkpoints/')),
                ('file_size_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('val_loss', models.FloatField(blank=True, null=True)),
                ('bleu_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('training_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='training.trainingrun')),
            ],
            options={
                'db_table': 'model_checkpoints',
                'ordering': ['training_run', '-epoch'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('split', models.CharField(default='test', max_length=20)),
                ('bleu_1', models.FloatField(blank=True, null=True)),
                ('bleu_2', models.FloatField(blank=True, null=True)),
                ('bleu_3', models.FloatField(blank=True, null=True)),
                ('bleu_4', models.FloatField(blank=True, null=True)),
                ('wer', models.FloatField(blank=True, null=True)),
                ('cer', models.FloatField(blank=True, null=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('f1_score', models.FloatField(blank=True, null=True)),
                ('per_sample_results', models.JSONField(default=list)),
                ('confusion_data', models.JSONField(default=dict)),
                ('num_samples_evaluated', models.PositiveIntegerField()),
                ('inference_time_ms', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checkpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='training.modelcheckpoint')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='datasets.dataset')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestures.language')),
            ],
            options={
                'db_table': 'evaluation_results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epoch', models.PositiveIntegerField()),
                ('step', models.PositiveIntegerField(blank=True, null=True)),
                ('train_loss', models.FloatField()),
                ('val_loss', models.FloatField(blank=True, null=True)),
                ('bleu_score', models.FloatField(blank=True, null=True)),
                ('wer', models.FloatField(blank=True, help_text='Word Error Rate', null=True)),
                ('cer', models.FloatField(blank=True, help_text='Character Error Rate', null=True)),
                ('additional_metrics', models.JSONField(default=dict)),
                ('epoch_duration_seconds', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('training_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='training.trainingrun')),
            ],
            options={
                'db_table': 'training_metrics',
                'ordering': ['training_run', 'epoch'],
                'unique_together': {('training_run', 'epoch')},
            },
        ),
    ]
