# Generated by Django 4.2.27 on 2026-01-06 03:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datasets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GestureSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('gloss', models.CharField(help_text='Sign gloss notation', max_length=255)),
                ('transcript', models.TextField(help_text='Text translation of the gesture')),
                ('capture_method', models.CharField(choices=[('depth_sensor', 'Depth Sensor'), ('mediapipe', 'MediaPipe'), ('mocap', 'Motion Capture'), ('synthetic', 'Synthetic'), ('other', 'Other')], default='mediapipe', max_length=20)),
                ('num_frames', models.PositiveIntegerField()),
                ('fps', models.PositiveIntegerField(default=30)),
                ('duration_ms', models.PositiveIntegerField(help_text='Duration in milliseconds')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('validated', 'Validated'), ('rejected', 'Rejected'), ('needs_review', 'Needs Review')], default='pending', max_length=20)),
                ('quality_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('raw_data_file', models.FileField(blank=True, upload_to='gestures/raw/')),
                ('processed_data_file', models.FileField(blank=True, upload_to='gestures/processed/')),
                ('recorded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='samples', to='datasets.dataset')),
            ],
            options={
                'db_table': 'gesture_samples',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GestureTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#6366f1', max_length=7)),
            ],
            options={
                'db_table': 'gesture_tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='ISO-style code (e.g., ASL, BdSL)', max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('num_signers', models.PositiveIntegerField(default=0, help_text='Estimated number of users')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'languages',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcript_type', models.CharField(choices=[('primary', 'Primary'), ('alternative', 'Alternative'), ('gloss', 'Gloss Notation'), ('phonetic', 'Phonetic')], default='primary', max_length=20)),
                ('text', models.TextField()),
                ('target_language', models.CharField(default='en', help_text='Target spoken language code (e.g., en, bn)', max_length=10)),
                ('confidence', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('annotated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcripts', to='gestures.gesturesample')),
            ],
            options={
                'db_table': 'transcripts',
                'ordering': ['sample', '-confidence'],
            },
        ),
        migrations.CreateModel(
            name='JointDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('joint_type', models.CharField(choices=[('hand', 'Hand'), ('arm', 'Arm'), ('body', 'Body'), ('face', 'Face')], max_length=20)),
                ('index', models.PositiveIntegerField(help_text='Joint index in skeleton array', unique=True)),
                ('description', models.TextField(blank=True)),
                ('parent_joint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_joints', to='gestures.jointdefinition')),
            ],
            options={
                'db_table': 'joint_definitions',
                'ordering': ['index'],
            },
        ),
        migrations.AddField(
            model_name='gesturesample',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='gestures.language'),
        ),
        migrations.AddField(
            model_name='gesturesample',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_samples', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gesturesample',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_samples', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='JointFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_index', models.PositiveIntegerField()),
                ('timestamp_ms', models.PositiveIntegerField()),
                ('joints_data', models.JSONField()),
                ('confidence_scores', models.JSONField(blank=True, null=True)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='gestures.gesturesample')),
            ],
            options={
                'db_table': 'joint_frames',
                'ordering': ['sample', 'frame_index'],
                'indexes': [models.Index(fields=['sample', 'frame_index'], name='joint_frame_sample__28b061_idx')],
                'unique_together': {('sample', 'frame_index')},
            },
        ),
        migrations.CreateModel(
            name='GestureSampleTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='gestures.gesturesample')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='gestures.gesturetag')),
            ],
            options={
                'db_table': 'gesture_sample_tags',
                'unique_together': {('sample', 'tag')},
            },
        ),
        migrations.AddIndex(
            model_name='gesturesample',
            index=models.Index(fields=['language', 'status'], name='gesture_sam_languag_b618b8_idx'),
        ),
        migrations.AddIndex(
            model_name='gesturesample',
            index=models.Index(fields=['gloss'], name='gesture_sam_gloss_824885_idx'),
        ),
        migrations.AddIndex(
            model_name='gesturesample',
            index=models.Index(fields=['created_at'], name='gesture_sam_created_34179c_idx'),
        ),
    ]
