# Generated by Django 4.2.27 on 2026-01-07 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gestures", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FaceFrame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("frame_index", models.PositiveIntegerField()),
                ("timestamp_ms", models.PositiveIntegerField()),
                ("landmarks", models.JSONField()),
                (
                    "mouth_crop",
                    models.ImageField(
                        blank=True, null=True, upload_to="gestures/face_crops/"
                    ),
                ),
                (
                    "sample",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="face_frames",
                        to="gestures.gesturesample",
                    ),
                ),
            ],
            options={
                "db_table": "face_frames",
                "ordering": ["sample", "frame_index"],
                "indexes": [
                    models.Index(
                        fields=["sample", "frame_index"],
                        name="face_frames_sample__64b566_idx",
                    )
                ],
                "unique_together": {("sample", "frame_index")},
            },
        ),
    ]
