# Generated by Django 4.2.27 on 2026-01-06 03:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('training', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelDeployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('deprecated', 'Deprecated')], default='inactive', max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('avg_inference_time_ms', models.FloatField(blank=True, null=True)),
                ('total_requests', models.PositiveBigIntegerField(default=0)),
                ('deployed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checkpoint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deployments', to='training.modelcheckpoint')),
                ('supported_languages', models.ManyToManyField(related_name='model_deployments', to='gestures.language')),
            ],
            options={
                'db_table': 'model_deployments',
                'ordering': ['-deployed_at'],
            },
        ),
        migrations.CreateModel(
            name='InferenceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('input_type', models.CharField(choices=[('live_stream', 'Live Stream'), ('uploaded_file', 'Uploaded File'), ('sample_reference', 'Sample Reference')], default='uploaded_file', max_length=20)),
                ('input_file', models.FileField(blank=True, upload_to='inference/inputs/')),
                ('num_frames', models.PositiveIntegerField(blank=True, null=True)),
                ('predicted_text', models.TextField(blank=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('token_confidences', models.JSONField(default=list)),
                ('beam_results', models.JSONField(default=list, help_text='Top-k beam search results')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('processing_time_ms', models.FloatField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checkpoint', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inference_requests', to='training.modelcheckpoint')),
                ('input_sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inference_requests', to='gestures.gesturesample')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('source_language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestures.language')),
            ],
            options={
                'db_table': 'inference_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InferenceFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('correct', 'Correct'), ('partially_correct', 'Partially Correct'), ('incorrect', 'Incorrect')], max_length=20)),
                ('corrected_text', models.TextField(blank=True, help_text='User-provided correct translation')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inference_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='inference.inferencerequest')),
                ('provided_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inference_feedback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='inferencerequest',
            index=models.Index(fields=['status', 'created_at'], name='inference_r_status_dda2d2_idx'),
        ),
    ]
